version: '3'

services:
  user-service:
    build:
      context: ./linebot
    image: chatbot
    environment:
      - FLASK_APP=server.py
    ports:
      - "5000"
    networks:
      - my-network
    labels:
      - "traefik.http.routers.user.rule=Host(`user.localhost`)"


